#!/bin/bash
#rm products.db


if  [ "$1" == "api" ]
then	
	if [ ! -f products.db ] ; then 
		echo "Database does not exist yet ... create db"
		touch products.db
		sqlite3 products.db ".read productDB.sql"
	fi
	echo "Activate virtual environment and start api ..."
	. venv/bin/activate
	python api.py
fi

if [ "$1" == "spider" ]
then
	echo "run the spider ..."
	cd lystCrawler/lystCrawler
	scrapy crawl lyst
fi

if [ "$1" == "test" ]
then
	ps cax | grep "python api.py" > /dev/null
	if [ $? -eq 0 ]; then
		echo "Process is running."
	else
		echo "Process is not running."
	fi
fi
exit

